name: Weekly pre-commit autoupdate

on:
  schedule:
    - cron: '0 3 * * 1'  # every Monday at 03:00 UTC

permissions:
  contents: read

jobs:
  autoupdate-pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.COMMIT_KEY }}
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true
      - name: Install pre-commit
        run: uv tool install pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate --freeze
      - name: Check for changes
        id: git-check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pre-commit-config.yaml
          if git diff --cached --quiet; then
            echo "no-changes=true" >> $GITHUB_OUTPUT
          else
            echo "no-changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push changes
        if: steps.git-check.outputs.no-changes == 'false'
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: "chore: pre-commit autoupdate"
          branch: chore-precommit-autoupdate
          title: "chore: pre-commit autoupdate"
          body: |
            This PR updates the dependencies in `.pre-commit-config.yaml` to the latest version
